name: github.com-kemadev-iac-components-deploy-github-30-repo
description: Pulumi stack template for infrastructure as code components
runtime: go
config:
  pulumi:disable-default-providers:
    description: Disable default providers to enforce using configured ones
    value:
      - '*'
  pulumi:tags:
    value:
      pulumi:template: /home/kema/dev/git/github.com/kemadev/iac-components/pkg/pulumi/stack-template
